### ISSUE TITLE
minor Typos in german admin manual

### ISSUE THREAD

**Issue by nfaupel** [effektif/admin-docs#28]
Page 1.
Front End-Applikationsdateien -->Front-End-Applikationsdateien
Back End-Anwendung --> Back-End-Anwendung

Page 2. 
Email-Server --> E-Mail-Server
Kommandozeilen-Beispielen --> Kommandozeilenbeispielen

**Comment by frontendphil** [comment]
We'd be more than happy for a PR :)

**Comment by TimKam** [comment]
Better: "Frontend", "Backend" (there is no "official" way of spelling this in German and that's how most people use it)
